#!/bin/bash

for f in $(ls *.contigs.fasta);
do ~/ncbi-blast-2.9.0/bin/blastn -query $f -db ~/ncbi-blast-2.9.0/db/flu -max_target_seqs 10 -outfmt "10 qseqid length stitle" -out ${f/.contigs.fasta/.csv};

done	

