#!bin/bash

docker run  -v /Volumes/TOSHIBA/20190410:/trans miniflu ./nanopolish variants --ploidy 1 -r ../trans/trim/BC01_trim.fastq -b ../trans/map/BC01.bam -g ../trans/map/ref_PR8_MH785011.fasta -o ../trans/vcf/BC01-PB2 -w "PR8_PB2:1-10000"

docker run  -v /Volumes/TOSHIBA/20190410:/trans miniflu ./nanopolish variants --ploidy 1 -r ../trans/trim/BC01_trim.fastq -b ../trans/map/BC01.bam -g ../trans/map/ref_PR8_MH785011.fasta -o ../trans/vcf/BC01-PB1 -w "PR8_PB1:1-10000"

docker run  -v /Volumes/TOSHIBA/20190410:/trans miniflu ./nanopolish variants --ploidy 1 -r ../trans/trim/BC01_trim.fastq -b ../trans/map/BC01.bam -g ../trans/map/ref_PR8_MH785011.fasta -o ../trans/vcf/BC01-PA -w "PR8_PA:1-10000"

docker run  -v /Volumes/TOSHIBA/20190410:/trans miniflu ./nanopolish variants --ploidy 1 -r ../trans/trim/BC01_trim.fastq -b ../trans/map/BC01.bam -g ../trans/map/ref_PR8_MH785011.fasta -o ../trans/vcf/BC01-HA -w "PR8_HA:1-10000"

docker run  -v /Volumes/TOSHIBA/20190410:/trans miniflu ./nanopolish variants --ploidy 1 -r ../trans/trim/BC01_trim.fastq -b ../trans/map/BC01.bam -g ../trans/map/ref_PR8_MH785011.fasta -o ../trans/vcf/BC01-NP -w "PR8_NP:1-10000"

docker run  -v /Volumes/TOSHIBA/20190410:/trans miniflu ./nanopolish variants --ploidy 1 -r ../trans/trim/BC01_trim.fastq -b ../trans/map/BC01.bam -g ../trans/map/ref_PR8_MH785011.fasta -o ../trans/vcf/BC01-NA -w "PR8_NA:1-10000"

docker run  -v /Volumes/TOSHIBA/20190410:/trans miniflu ./nanopolish variants --ploidy 1 -r ../trans/trim/BC01_trim.fastq -b ../trans/map/BC01.bam -g ../trans/map/ref_PR8_MH785011.fasta -o ../trans/vcf/BC01-M -w "PR8_MP:1-10000"

docker run  -v /Volumes/TOSHIBA/20190410:/trans miniflu ./nanopolish variants --ploidy 1 -r ../trans/trim/BC01_trim.fastq -b ../trans/map/BC01.bam -g ../trans/map/ref_PR8_MH785011.fasta -o ../trans/vcf/BC01-NA -w "PR8_NS:1-10000"

