#!bin/bash

~/samtools-1.9/bin/samtools faidx map/ref_PR8_MH785011.fasta

~/samtools-1.9/bin/samtools view -bS ./map/BC01.sam | ~/samtools-1.9/bin/samtools sort -o ./map/BC01.bam

~/samtools-1.9/bin/samtools index -b ./map/BC01.bam ./map/BC01.bai


